import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getTokenFromRequest, verifyToken } from "@/lib/auth";

const SEED_DATA = [
  {
    startupName:  "DScribe",
    founderName:  "Aditya Kulkarni",
    founderEmail: "aditya@dscribe.in",
    founderPhone: "+91 98450 11234",
    program:      "Vridhi",
    stage:        "MVP",
    mentor:       "Dr. Ramesh Kumar",
    description:  "DScribe is an AI-powered document intelligence platform that automates extraction, classification, and summarization of enterprise documents, reducing manual processing time by 80%.",
    fundingStage: "Grant Supported",
    progress:     65,
    status:       "Active",
    website:      "https://dscribe.in",
    industry:     "SaaS / AI",
    teamSize:     6,
    location:     "Bengaluru, Karnataka",
  },
  {
    startupName:  "Agrils",
    founderName:  "Priya Nair",
    founderEmail: "priya@agrils.com",
    founderPhone: "+91 97440 22345",
    program:      "Diksuchi",
    stage:        "Prototype",
    mentor:       "Prof. Sunita Sharma",
    description:  "Agrils connects smallholder farmers directly to bulk buyers using a mobile-first marketplace with AI-driven price discovery and logistics coordination for perishables.",
    fundingStage: "Bootstrapped",
    progress:     40,
    status:       "Active",
    website:      "https://agrils.com",
    industry:     "AgriTech",
    teamSize:     4,
    location:     "Mysuru, Karnataka",
  },
  {
    startupName:  "Ecoveer",
    founderName:  "Sanjay Mehta",
    founderEmail: "sanjay@ecoveer.io",
    founderPhone: "+91 96360 33456",
    program:      "Vridhi",
    stage:        "Idea",
    mentor:       "Mr. Vikram Nair",
    description:  "Ecoveer gamifies sustainability for urban households by tracking their carbon footprint and rewarding green behavior with verified carbon credits redeemable at partner brands.",
    fundingStage: "Bootstrapped",
    progress:     25,
    status:       "Active",
    website:      null,
    industry:     "CleanTech",
    teamSize:     3,
    location:     "Pune, Maharashtra",
  },
  {
    startupName:  "SafeCloak",
    founderName:  "Rohan Desai",
    founderEmail: "rohan@safecloak.tech",
    founderPhone: "+91 95270 44567",
    program:      "Vega",
    stage:        "MVP",
    mentor:       "Dr. Priya Patel",
    description:  "SafeCloak provides zero-trust endpoint security for SMEs through a lightweight agent that detects and neutralizes insider threats in real time without heavy IT infrastructure.",
    fundingStage: "Pre-Seed",
    progress:     70,
    status:       "Active",
    website:      "https://safecloak.tech",
    industry:     "CyberSecurity",
    teamSize:     7,
    location:     "Hyderabad, Telangana",
  },
  {
    startupName:  "Curilearn",
    founderName:  "Meghana Rao",
    founderEmail: "meghana@curilearn.com",
    founderPhone: "+91 94180 55678",
    program:      "Yuva Shristi",
    stage:        "Funding",
    mentor:       "Mr. Anil Verma",
    description:  "Curilearn delivers hyper-personalized K-12 STEM education through adaptive micro-courses, live doubt sessions, and project-based learning in regional languages.",
    fundingStage: "Seed",
    progress:     80,
    status:       "Active",
    website:      "https://curilearn.com",
    industry:     "EdTech",
    teamSize:     12,
    location:     "Chennai, Tamil Nadu",
  },
  {
    startupName:  "RevuteAI",
    founderName:  "Arjun Krishnan",
    founderEmail: "arjun@revuteai.com",
    founderPhone: "+91 93090 66789",
    program:      "Vega",
    stage:        "Growth",
    mentor:       "Prof. Meena Krishnan",
    description:  "RevuteAI automates B2B sales workflows using conversational AI that qualifies leads, schedules demos, and drafts proposals — compressing a 14-day sales cycle to 3 days.",
    fundingStage: "Series A",
    progress:     88,
    status:       "Active",
    website:      "https://revuteai.com",
    industry:     "Artificial Intelligence",
    teamSize:     18,
    location:     "Bengaluru, Karnataka",
  },
  {
    startupName:  "Hyper Bharat",
    founderName:  "Kavitha Sundaram",
    founderEmail: "kavitha@hyperbharat.in",
    founderPhone: "+91 92000 77890",
    program:      "Vridhi",
    stage:        "Prototype",
    mentor:       "Dr. Ramesh Kumar",
    description:  "Hyper Bharat is a last-mile EV logistics network for Tier 2 and Tier 3 Indian cities, using shared electric cargo bikes and a real-time fleet management platform.",
    fundingStage: "Grant Supported",
    progress:     38,
    status:       "Active",
    website:      "https://hyperbharat.in",
    industry:     "Logistics & Mobility",
    teamSize:     9,
    location:     "Coimbatore, Tamil Nadu",
  },
  {
    startupName:  "TracTree",
    founderName:  "Nikhil Patil",
    founderEmail: "nikhil@tractree.org",
    founderPhone: "+91 91910 88901",
    program:      "Diksuchi",
    stage:        "Idea",
    mentor:       "Prof. Sunita Sharma",
    description:  "TracTree uses satellite imagery and IoT soil sensors to provide smallholder farmers with precise, real-time crop health monitoring and predictive pest alerts.",
    fundingStage: "Bootstrapped",
    progress:     20,
    status:       "Active",
    website:      null,
    industry:     "Environmental Tech",
    teamSize:     3,
    location:     "Nagpur, Maharashtra",
  },
  {
    startupName:  "Rosette Smart Life",
    founderName:  "Divya Pillai",
    founderEmail: "divya@rosettesmartlife.com",
    founderPhone: "+91 90820 99012",
    program:      "Vega",
    stage:        "MVP",
    mentor:       "Mr. Vikram Nair",
    description:  "Rosette Smart Life offers plug-and-play IoT retrofit kits that convert legacy home appliances into smart devices controlled via a unified voice and app interface.",
    fundingStage: "Pre-Seed",
    progress:     60,
    status:       "Active",
    website:      "https://rosettesmartlife.com",
    industry:     "IoT & Smart Home",
    teamSize:     5,
    location:     "Kochi, Kerala",
  },
  {
    startupName:  "Snow-Zoe Technologies",
    founderName:  "Farhan Siddiqui",
    founderEmail: "farhan@snowzoe.tech",
    founderPhone: "+91 89730 10123",
    program:      "Yuva Shristi",
    stage:        "Prototype",
    mentor:       "Dr. Priya Patel",
    description:  "Snow-Zoe Technologies develops AR-powered retail try-on experiences for fashion and eyewear brands, reducing returns by 40% and boosting online conversion rates.",
    fundingStage: "Bootstrapped",
    progress:     45,
    status:       "Active",
    website:      "https://snowzoe.tech",
    industry:     "AR / Retail Tech",
    teamSize:     6,
    location:     "Mumbai, Maharashtra",
  },
  {
    startupName:  "OneShell",
    founderName:  "Shreya Iyer",
    founderEmail: "shreya@oneshell.io",
    founderPhone: "+91 88640 21234",
    program:      "Vridhi",
    stage:        "Funding",
    mentor:       "Mr. Anil Verma",
    description:  "OneShell is a unified developer platform that consolidates cloud infrastructure management, CI/CD pipelines, and observability into a single dashboard for engineering teams.",
    fundingStage: "Seed",
    progress:     75,
    status:       "Active",
    website:      "https://oneshell.io",
    industry:     "Developer Tools",
    teamSize:     10,
    location:     "Bengaluru, Karnataka",
  },
  {
    startupName:  "Kakud",
    founderName:  "Tejasvi Reddy",
    founderEmail: "tejasvi@kakud.app",
    founderPhone: "+91 87550 32345",
    program:      "Diksuchi",
    stage:        "Prototype",
    mentor:       "Prof. Meena Krishnan",
    description:  "Kakud is a community commerce platform enabling local artisans and home-based entrepreneurs to build digital storefronts, manage inventory, and accept UPI payments with zero technical know-how.",
    fundingStage: "Bootstrapped",
    progress:     32,
    status:       "Active",
    website:      "https://kakud.app",
    industry:     "Consumer Tech",
    teamSize:     4,
    location:     "Vijayawada, Andhra Pradesh",
  },
  {
    startupName:  "VeloData",
    founderName:  "Rahul Nambiar",
    founderEmail: "rahul@velodata.ai",
    founderPhone: "+91 86460 43456",
    program:      "Vega",
    stage:        "MVP",
    mentor:       "Dr. Ramesh Kumar",
    description:  "VeloData provides a real-time data streaming and analytics platform for manufacturing plants, enabling predictive maintenance and quality control at 1/10th the cost of traditional SCADA systems.",
    fundingStage: "Grant Supported",
    progress:     58,
    status:       "Active",
    website:      "https://velodata.ai",
    industry:     "Industrial Analytics",
    teamSize:     8,
    location:     "Pune, Maharashtra",
  },
  {
    startupName:  "NutriPath",
    founderName:  "Asha Murthy",
    founderEmail: "asha@nutripath.in",
    founderPhone: "+91 85370 54567",
    program:      "Yuva Shristi",
    stage:        "Growth",
    mentor:       "Prof. Sunita Sharma",
    description:  "NutriPath offers AI-driven personalized nutrition coaching using blood biomarker data and continuous glucose monitoring to help individuals manage metabolic health proactively.",
    fundingStage: "Series A",
    progress:     82,
    status:       "Active",
    website:      "https://nutripath.in",
    industry:     "HealthTech",
    teamSize:     15,
    location:     "Bengaluru, Karnataka",
  },
  {
    startupName:  "UrbanCanvas",
    founderName:  "Kiran Joshi",
    founderEmail: "kiran@urbancanvas.studio",
    founderPhone: "+91 84280 65678",
    program:      "Diksuchi",
    stage:        "Scaling",
    mentor:       "Mr. Vikram Nair",
    description:  "UrbanCanvas is an on-demand interior design platform that connects verified designers with urban homeowners and uses 3D visualization to deliver design plans within 48 hours.",
    fundingStage: "Series B",
    progress:     92,
    status:       "Graduated",
    website:      "https://urbancanvas.studio",
    industry:     "PropTech / Design",
    teamSize:     32,
    location:     "Mumbai, Maharashtra",
  },
];

export async function POST(req: NextRequest) {
  const token = getTokenFromRequest(req);
  if (!token) return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  const payload = verifyToken(token);
  if (!payload) return NextResponse.json({ error: "Invalid session." }, { status: 401 });

  const caller = await prisma.employee.findUnique({
    where: { id: payload.id },
    select: { role: true },
  });
  if (!caller || caller.role !== "admin")
    return NextResponse.json({ error: "Forbidden." }, { status: 403 });

  const existing = await prisma.startup.count();
  if (existing > 0) {
    return NextResponse.json(
      { message: `Seed skipped — ${existing} startup(s) already exist.`, skipped: true },
      { status: 200 }
    );
  }

  const created = await prisma.startup.createMany({ data: SEED_DATA });

  return NextResponse.json({
    message: `Successfully seeded ${created.count} startups.`,
    count: created.count,
  });
}
